apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: buxo1kdhe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: buxo1kdhe-go 
  name: buxo1kdhe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: buxo1kdhe-go 
